package com.fx.gui;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*tt.java
 *
 * Created on __DATE__, __TIME__
 */


/**
 *银行客户端界面
 * @author  __USER__
 */
public class Client extends javax.swing.JFrame {
	String idcard;
	/** Creates new form tt */
	JLabel jLabel3;
	public Client(String idcard) {
		this.idcard=idcard;
		initComponents();
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		
		setIconImage(getToolkit().getImage(getClass().getResource("/images/1.jpg")));
		jLabel3=new JLabel();
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jButton1.setFont(new java.awt.Font("宋体", 0, 24));
		jButton1.setText("修改密码");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new ChangePwd(idcard,Client.this).setVisible(true);
				}
		});
		getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1,
						-1));

		
		jLabel1.setFont(new java.awt.Font("宋体", 0, 36));
		jLabel1.setText("银行管理系统");
		getContentPane().add(
				jLabel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1,
						-1));

		jButton2.setFont(new java.awt.Font("宋体", 0, 24));
		jButton2.setText("货币兑换");
		getContentPane().add(
				jButton2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1,
						-1));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new ExMoney(idcard,Client.this).setVisible(true);
			}
		});

		jButton3.setFont(new java.awt.Font("宋体", 0, 24));
		jButton3.setText(" 存款 ");
		getContentPane().add(
				jButton3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250,
						130, -1));
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new AddMoney(idcard,Client.this).setVisible(true);
			}
		});

		jButton4.setFont(new java.awt.Font("宋体", 0, 24));
		jButton4.setText(" 取款 ");
		getContentPane().add(
				jButton4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350,
						130, -1));
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new DeMoney(idcard,Client.this).setVisible(true);
			}
		});

		jButton5.setFont(new java.awt.Font("宋体", 0, 24));
		jButton5.setText("查询余额");
		getContentPane().add(
				jButton5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1,
						-1));
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new QueryMoney(idcard,Client.this).setVisible(true);
			}
		});

		
		jButton6.setFont(new java.awt.Font("宋体", 0, 24));
		jButton6.setText(" 转账 ");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				new ToUMoney(idcard,Client.this).setVisible(true);
			}
		});
		getContentPane().add(
				jButton6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150,
						130, -1));

		jButton7.setFont(new java.awt.Font("宋体", 0, 24));
		jButton7.setText("退出系统");
		getContentPane().add(
				jButton7,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460,
						260, -1));
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				closeFrame();
			}
		});
		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/gehu.jpg"))); // NOI18N
		getContentPane()
				.add(jLabel3,
						new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0,
								-1, -1));
		this.setTitle("银行客户端");
		this.setSize(1000,600);
		this.setLocationRelativeTo(null);
		this.setResizable(false);
	}// </editor-fold>
	//GEN-END:initComponents


	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Client("123456789").setVisible(true);
			}
		});
	}
	private void closeFrame() {
		int a = JOptionPane.showConfirmDialog(null, "确定退出系统吗？", "确定关闭",
				JOptionPane.YES_NO_OPTION);
		if (a == JOptionPane.YES_OPTION) {
			dispose();
		}
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}
