/*
 * ExMoney.java
 *
 * Created on __DATE__, __TIME__
 */

package com.fx.gui;

import java.math.BigDecimal;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.fx.bean.UCash;
import com.fx.dao.CashDao;

/**
 *外币兑换界面
 * @author  __USER__
 */
public class ExMoney extends javax.swing.JDialog {
	private String idcard;
	private double pm2[]={6.410,7.857,0.058,0.006,};
	private String[] pm1=new String[] {" 美  元 ", " 欧  元 ", " 日  元 ", " 韩  元 " };
	/** Creates new form ExMoney */
	public ExMoney(String idcard,JFrame jf) {
		super(jf,true);
		this.idcard=idcard;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {	

		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		setIconImage(getToolkit().getImage(getClass().getResource("/images/1.jpg")));
		jLabel3.setText("jLabel3");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel1.setText("请输入兑换金额：");
		getContentPane().add(
				jLabel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1,
						-1));

		getContentPane().add(
				jTextField1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 150,
						-1));

		jLabel2.setText("请选择货币类型：");
		getContentPane().add(
				jLabel2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1,
						-1));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(pm1));
		getContentPane().add(
				jComboBox1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1,
						-1));

		jButton1.setText("确认");
		getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100,
						-1));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {//外币兑换功能实现
				String tmoney=jTextField1.getText().toString().trim();	
				if(tmoney.equals(""))
				{	JOptionPane.showMessageDialog(null, "没有输入金额！");
					return;
				}
				CashDao cdao=new CashDao();
				Double money1 =Double.valueOf(tmoney);
				int i=jComboBox1.getSelectedIndex();
				Double money2=new BigDecimal(money1*pm2[i]).setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();
				UCash uc=cdao.queryUCashone(idcard);
				if(money1<=0)
				{	JOptionPane.showMessageDialog(null, "金额输入必须大于0！");
					return;
				}
				else if(uc.getEndCash()-money2<0)
				{	JOptionPane.showMessageDialog(null, "余额不足！");
					return;
				}
				else
				{	
					uc.setEndCash(uc.getEndCash()-money2);
					cdao.updateCash(uc);
					
					JOptionPane.showMessageDialog(null, "兑换成功，共花费人民币"+money2+"元，余额："+uc.getEndCash()+"元！");
					dispose();
				}
				
				
			}
		});

		jButton2.setText("取消");
		getContentPane().add(
				jButton2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 90,
						-1));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dispose();
			}
		});
		this.setTitle("银行客户端");
		this.setSize(420,320);
		this.setLocationRelativeTo(null);
		this.setResizable(false);
	}// </editor-fold>
	//GEN-END:initComponents


	/**
	 * @param args the command line arguments
	 */


	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}
