/*
 * ToUMoney1.java
 *
 * Created on __DATE__, __TIME__
 */

package com.fx.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import com.fx.bean.UCash;
import com.fx.dao.CashDao;

/**
 *	银行客户端转账界面
 * @author  __USER__
 */
public class ToUMoney extends javax.swing.JDialog {
	private String idcard;
	/** Creates new form ToUMoney1 */
	public ToUMoney(String idcard,JFrame jf) {
		super(jf,true);
		this.idcard=idcard;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		setIconImage(getToolkit().getImage(getClass().getResource("/images/1.jpg")));
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		getContentPane().add(
				jTextField1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 55, 170,
						30));
		getContentPane().add(
				jTextField2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 131,
						170, 30));

		jLabel2.setText("请输入转账卡号：");
		getContentPane().add(
				jLabel2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1,
						-1));

		jLabel1.setText("请输入转账金额：");
		getContentPane().add(
				jLabel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 135, -1,
						-1));

		jButton1.setText("确认");
		getContentPane().add(
				jButton1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 215, 100,
						30));
		jButton1.addActionListener(new ActionListener() {//对输入卡号，金额进行判定并对数据库进行操作完成转账功能
			public void actionPerformed(final ActionEvent e) {
				String yidcard=jTextField1.getText().toString().trim();
				String smoeny=jTextField2.getText().toString().trim();
				if(yidcard.equals(""))
				{	JOptionPane.showMessageDialog(null, "没有输入卡号！");
					return;
				}
				if(smoeny.equals(""))
				{	JOptionPane.showMessageDialog(null, "没有输入金额！");
					return;
				}
				CashDao cdao=new CashDao();
				Double money =Double.valueOf(smoeny);
				UCash uc1=cdao.queryUCashone(idcard);
				UCash uc2=cdao.queryUCashone(yidcard);
				if(uc2==null)
				{	JOptionPane.showMessageDialog(null, "输入卡号有误！");
				}
				else if(uc2.getIdcard().equals(uc1.getIdcard()))
				{	JOptionPane.showMessageDialog(null, "不能给本卡转账！");
					
				}
				else if(money<=0)
				{	JOptionPane.showMessageDialog(null, "金额输入必须大于0！");
					
				}
				else if(uc1.getEndCash()-money<0)
				{	JOptionPane.showMessageDialog(null, "余额不足！");
					
				}
				else
				{	uc2.setEndCash(uc2.getEndCash()+money);
					uc1.setEndCash(uc1.getEndCash()-money);
					cdao.updateCash(uc1);
					cdao.updateCash(uc2);
					JOptionPane.showMessageDialog(null, "转账成功！");
					dispose();
				}
					
			}
		});

		jButton2.setText("取消");
		getContentPane().add(
				jButton2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 215,
						100, 30));
		jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(final ActionEvent e) {
				dispose();
			}
		});

		this.setTitle("转账");
		this.setSize(420,320);
		this.setLocationRelativeTo(null);
		this.setResizable(false);
	}// </editor-fold>
	//GEN-END:initComponents

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}
